@Tyr_HostAddress = https://localhost:7198

#-----------SERVICES-----------
GET {{Tyr_HostAddress}}/servicos/
Accept: application/json

###

GET {{Tyr_HostAddress}}/servicos/1

###

PUT {{Tyr_HostAddress}}/servicos/1
Content-Type: application/json

{
  "nome":"Corte de Cabelo",
  "preco": 100
}

###

DELETE {{Tyr_HostAddress}}/servicos/1

###


#-----------PROFESSIONALS-----------

GET {{Tyr_HostAddress}}/profissionais

###

POST {{Tyr_HostAddress}}/profissionais
Content-Type: application/json

{
  "nome": "Bobao"
}
###

DELETE {{Tyr_HostAddress}}/profissionais/6

###

GET {{Tyr_HostAddress}}/profissionais/{id}

###

PUT {{Tyr_HostAddress}}/profissionais/{id}

###

@profissionalId=1
GET {{Tyr_HostAddress}}/profissionais/{{profissionalId}}/servicos

###

POST {{Tyr_HostAddress}}/profissionais/{{profissionalId}}/servicos
Content-Type: application/json

{
  "nome":"Barba",
  "preco": 10
}

###

#-----------CLIENTES-----------

@id=1
GET {{Tyr_HostAddress}}/Clientes

###

POST {{Tyr_HostAddress}}/Clientes
Content-Type: application/json

{
  "nome": "Gustavo resende",
  "telefone": "371238132883"
}

###

DELETE {{Tyr_HostAddress}}/Clientes/{{id}}

###

GET {{Tyr_HostAddress}}/Clientes/{{id}}

###

PUT {{Tyr_HostAddress}}/Clientes/{{id}}
Content-Type: application/json

{
  "name": "Gustavo Resende",
  "telefone": "371238132883"
}

###

#-----------AGENDAMENTOS-----------

GET {{Tyr_HostAddress}}/Agendamentos

###

POST {{Tyr_HostAddress}}/Agendamentos
Content-Type: application/json

{
  "horario": "2025-11-10T17:00:00Z",
  "clienteId": 2,
  "profissionalId": 1,
  "servicoId": 2
}

###

DELETE {{Tyr_HostAddress}}/Agendamentos/1

###
